version: '3.3'

services:
  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
#    command: php artisan migrate
    ports:
      - "8080:80"
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./services/app:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"

  composer:
    container_name: composer
    restart: 'no'
    image: composer
#    working_dir: /usr//html
    #  command: install
    depends_on:
      - app
#    volumes_from:
#      - app
