version: '3.3'

services:
  app:
    container_name: app
    build:
      context: services/app
      dockerfile: Dockerfile.development
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./services/app:/app"
      - "/tmp:/tmp:delegated"
      - "./services/app/.npm:/.npm"
      - ".services/app/.config:/.config"
      - ".env:/app/.env"
    depends_on:
      - db

  nginx:
    container_name: nginx
    build:
      context: services/nginx
      dockerfile: Dockerfile
    volumes:
      - "./services/nginx/articles.conf:/etc/nginx/conf.d/default.conf"
      - "./services/app/public:/app/public"
    ports:
      - "${PORT}:80"
    env_file:
      - .env
    depends_on:
      - app

  db:
    image: mysql
    restart: always
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306

  redis:
    image: redis

volumes:
  dbdata:
