version: '3.3'

services:
  app:
    container_name: app
    build:
      context: services/app
      dockerfile: Dockerfile.development
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./services/app:/usr/src/app"
      - "/tmp:/tmp:delegated"
      - "./services/app/.npm:/.npm"
      - ".env:/usr/src/app/.env"
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    build:
      context: services/nginx
      dockerfile: Dockerfile
    volumes:
      - "./services/nginx/articles.conf:/etc/nginx/conf.d/articles.conf"
      - "./services/app:/usr/src/app"
    ports:
      - "${PORT}:80"
    env_file:
      - .env
    depends_on:
      - app

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

volumes:
  dbdata:
