version: '3.3'

services:
  app:
    container_name: app
    build:
      context: services/app
      dockerfile: Dockerfile.development
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./services/app:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"
    env_file:
      - .env

  nginx:
    build:
      context: services/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - app

