version: '3.3'

services:
  app:
    container_name: app
    build:
      context: services/app
      dockerfile: Dockerfile.development
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./services/app:/usr/src/app"
      - "/tmp:/tmp:delegated"
      - "./services/app/.npm:/.npm"
    env_file:
      - .env

  nginx:
    build:
      context: services/nginx
      dockerfile: Dockerfile
    volumes:
      - "./services/nginx/articles.conf:/etc/nginx/conf.d/articles.conf"
      - "./services/app:/usr/src/app"
    ports:
      - "${PORT}:80"
    env_file:
      - .env
    depends_on:
      - app
