version: '3.3'

services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile.production
    env_file: ./.env.testing
    depends_on:
      - db
    command: vendor/bin/phpunit

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=tester
      - MYSQL_PASSWORD=secret
