version: '3.3'
  services:
    db:
      image: mysql
      environment:
        POSTGRES_USER: web

    sut:
      build:
        context: .
        dockerfile: Dockerfile.production
      command: make test
      depends_on:
        - db
