version: '3.3'
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile.production
    env_file: ../../.env
    environment:
      - APP_ENV=testing
      - TELESCOPE_ENABLED=false
    command: vendor/bin/phpunit
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
