version: '3.3'
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      - APP_ENV=testing
      - TELESCOPE_ENABLED=false
      - DB_HOST=db
      - DB_DATABASE=test_db
      - DB_PASSWORD=secret
      - DB_USERNAME=dev

    command: vendor/bin/phpunit
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=secret
