---
- hosts: webservers
  gather_facts: false
  vars_prompt:
    - name: "articles_image_tag"
      prompt: "Articles image tag"
      private: false

  tasks:
    - name: download nginx image
      docker_image:
        name: "{{ articles_nginx_image_name }}:{{ articles_image_tag }}"

    - name: download db
      docker_image:
        name: mysql

    - name: download app image
      docker_image:
        name: "{{ articles_app_image_name }}:{{ articles_image_tag }}"

    - name: run migrations
      docker_container:
        env:
          MYSQL_DATABASE: "{{ vault_db_name }}"
          MYSQL_USER: "{{ vault_db_user }}"
          MYSQL_ROOT_PASSWORD: "{{ vault_db_password }}"
          MYSQL_PASSWORD: "{{ vault_db_password }}"
        image: mysql
        name: app_migrations
        networks:
        - name: "{{ articles_docker_network }}"
        recreate: yes

        command: "php artisan migrate"
        volumes:
          - db_data:/var/lib/mysql
      run_once: yes

    - name: start app
      docker_container:
        recreate: yes
        name: app
        image: "{{ articles_app_image_name }}:{{ articles_image_tag }}"
        state: started
        env_file: "/root/.env"
        networks:
          - name: "{{ articles_docker_network }}"

    - name: start nginx
      docker_container:
        recreate: yes
        name: nginx
        image: "{{ articles_nginx_image_name }}:{{ articles_image_tag }}"
        state: startde
        restart_policy: always
        published_ports:
          - "80:80"
        networks:
          - name: "{{ articles_docker_network }}"
