---
- hosts: all
  gather_facts: no
  tasks:
    - template:
        src: environment.j2
        dest: '../.env'
      tags: env

    - template:
        src: mysql-init.j2
        dest: '../mysql-init.sql'
