---
- hosts: all
  gather_facts: no

  pre_tasks:
    - apt:
        update_cache: true
        name:
          - python3
          - python3-pip
      become: true

    - name: ensure group docker exists
      group:
        name: docker
      become: true

    - pip:
        name: docker
      become: true
